# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5222420a-99da-457c-88c0-a54f5bdb41e0";
      fsType = "ext4";
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/f945fdb1-78fe-4443-a4bd-3456f955cd38";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/7CB3-D62D";
      fsType = "vfat";  
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/981b71d0-5224-4965-bba3-43105ab60040";
      fsType = "ext4";
    };

  fileSystems."/var/media" = {
    device = "data/media";
    fsType = "zfs";
    options = [ "nofail" ];
  };

  fileSystems."/var/archive" = {
    device = "data/archive";
    fsType = "zfs";
    options = [ "nofail" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
