# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a4441990-2aeb-4353-98b4-23ae402d82bb";
      fsType = "ext4";
    };

  # fileSystems."/var/lib" =
  #   { device = "/dev/disk/by-uuid/82467efe-b39d-414b-82ec-f33f8c23020f";
  #     fsType = "ext4";
  #   };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/7CB3-D62D";
      fsType = "vfat";  
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # fileSystems."/home" =
  #   { device = "/dev/disk/by-uuid/1567721f-fee5-4f77-a0cb-19901910d943";
  #     fsType = "ext4";
  #   };

  # fileSystems."/var/media" =
  #   { device = "data/media";
  #     fsType = "zfs";
  #   };

  # fileSystems."/var/archive" =
  #   { device = "data/archive";
  #     fsType = "zfs";
  #   };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
