when:
  - event: push
    branch: main
  - event: manual
    branch: main

steps:
  - name: validate
    image: nixos/nix
    volumes:
      - nix-cache:/nix
    commands:
      - nix --extra-experimental-features "nix-command flakes" flake check -L --show-trace
