when:
  - event: push
  - event: manual

steps:
  - name: validate
    image: nixos/nix
    volumes:
      - nix-cache:/nix
      - /home/jake/.ssh:/root/.ssh:ro 
    commands:
      # check ssh is available first
      - cp -r /root/.ssh /tmp/ssh
      - chmod 700 /tmp/ssh
      - chmod 600 /tmp/ssh/*
      - export GIT_SSH_COMMAND="ssh -F /tmp/ssh/config -i /tmp/ssh/id_ed25519"
      - ssh -F /tmp/ssh/config -T git@github.com
      - nix --extra-experimental-features "nix-command flakes" flake check -L --show-trace --option sandbox false
  - name: enforce-main-pins
    image: alpine:3.20
    when:
      - branch: main
        event: push
      - branch: main
        event: manual
    commands:
      - ./scripts/check-main-branch-pins.sh
  # - name: deploy
  #   image: some-image
  #   when:
  #     - branch: main
  #       event: push
  #     - event: manual
  #       branch: main
  #   commands:
  #     - ./deploy.sh
