{ ... }:

{
    publicKeys = {
        turing = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL0q1CwSf4NG0jPtBtWabETld24LR2QsIB4XQLpukXSK jake@Jacobs-MacBook-Pro.local";
        shrike = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiydmkWP+geDEY0d5GxIzXfo56qpozxG9MSCJK9cWas jake@nixos-shrike";
        adler  = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMpAI5WnOeOfzd2kug6CrjvzRoCG0QA+wlDkLpn26H1f jake@adler";
        termius = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO9M0+nOa+uPnFcbStJwtgTtTR7SW2yBNY4+9BOQDLMx Generated By Termius";
    };

    # NOTE: peers must have this port set in their client wg0.conf under [Interface]
    wireguardPeers = {
        turing = {
            publicKey = "EjFLx48Wdx3HIun5f3lRZXJvSEJzU4B9zl8ydLVDxww=";
            ip = "10.9.0.2";
        };
        vega = {
            publicKey = "y3TyMBP8ogVt61NRLUy/EivrsOPkjS27LxDJ8zrMzlw=";
            ip = "10.9.0.3";
        };
        lstr = {
            publicKey = "DtZunhndCWtdJHwxujKzzJjE1ey/HmVY2AJzPjzWXww=";
            ip = "10.9.0.4";
        };
    };
}
